### ISSUE TITLE
Inform 7

### ISSUE THREAD

**Issue by samis** [pannous/english-script#3]
Both of these languages could provide interesting inspiration for the language. For Inform 7, it is a english-like domain-specific language the syntax of grammar of which could be useful for this own language. The [Inform 7 Recipe Book](http://inform7.com/learn/man/RB_1_1.html) has many examples of the language.

Random note: the Smalltalk syntax for message sending/method invocation seems that it might fit in well. Example: `Transcript show: 'Hello World!'`

**Comment by pannous** [comment]
Hi, we know and love Inform 7!

>Both of these languages could provide interesting inspiration for the language. 
which?
angle=english-script

>Smalltalk syntax 
nah, we rather stick with english:
`show transcript for 'Hello World!'`
